---
- hosts: all
  become: true

  vars:
    intellij_edition: community
    my_user: admin
    persistent_home: /mnt/share
    kb_model: pc105 
    kb_layout: gb
    locale: en_GB.UTF-8

  pre_tasks:
    - name: Update apt cache
      ansible.builtin.apt: update_cache=true cache_valid_time=86400

    - name: Update all packages to the latest version
      ansible.builtin.apt:
        upgrade: dist

  roles:

    # Install ubuntu tools
    - role: ubuntu
      tags:
        - gui
        - ubuntu

    # Install backup tools
    - role: backup
      tags:
        - gui
        - backup

    # Install tools
    - role: tools
      tags:
        - gui
        - tools

    # Install Browser
    - role: browsers
      tags:
        - gui
        - browser

    # Install image edtiros etc
    - role: graphic
      tags:
        - gui
        - graphic

    # Install music / audio
    - role: multimedia
      tags:
        - gui
        - multimedia

    # Install office
    - role: office
      tags:
        - gui
        - office

    # Install fonts
    - role: fonts
      tags:
        - fonts

    # Install vm tools
    # - role: vm
    #   tags:
    #     - gui
    #     - vm

  post_tasks:
    # Cleanup
    - name: Remove dependencies that are no longer required
      ansible.builtin.apt:
        autoremove: true

    - name: Remove obsolete packages from the cache
      ansible.builtin.apt:
        autoclean: true
