---
- src: geerlingguy.docker
  version: '6.2.0'
- src: weareinteractive.environment
  version: '1.5.0'
- src: geerlingguy.nodejs
  version: '6.1.1'
- src: oefenweb.locales
  version: 'v1.0.48'
- src: gantsign.git_user
  version: '1.2.0'
- src: gantsign.inotify
  version: '1.2.2'
- src: gantsign.intellij
- src: gantsign.intellij_jdks
  version: '2.0.1'
- src: gantsign.intellij-plugins
  version: '3.1.1'
- src: gantsign.java
  version: '11.1.5'
- src: gantsign.keyboard
  version: '1.5.0'
- src: gantsign.maven
  version: '5.7.4'
- src: gantsign.pyenv
  version: '2.0.0'
- src: gantsign.sdkman
  version: '2.2.0'
- src: gantsign.sdkman_init
  version: '1.2.2'
- src: gantsign.timezone
  version: '1.1.1'
- src: gantsign.visual-studio-code
  version: '7.0.0'
- src: gantsign.visual-studio-code-extensions
  version: '2.4.0'
- src: gantsign.lightdm
  version: 'v3.0.1'
- src: https://github.com/gantsign/ansible-role-xdesktop/archive/6.1.1.tar.gz
  name: gantsign.xdesktop
- src: andrewrothstein.starship
  version: 'v1.1.5'
- src: gantsign.postman
  version: '2.4.0'