---
- hosts: all
  become: true

  vars:
    locale: en_GB.UTF-8

  pre_tasks:
    - name: Update apt cache
      ansible.builtin.apt: update_cache=true cache_valid_time=86400

    - name: Update all packages to the latest version
      ansible.builtin.apt:
        upgrade: dist

  roles:

    - role: starship
      tags:
        - terminal
        - gui

    - role: drawio
      tags:
        - graphic
        - gui

    - role: slack
      tags:
        - com
        - gui

  post_tasks:
    # Cleanup
    - name: Remove dependencies that are no longer required
      ansible.builtin.apt:
        autoremove: true

    - name: Remove obsolete packages from the cache
      ansible.builtin.apt:
        autoclean: true
