---
- name: Install nvm
  ansible.builtin.shell: >
    curl -o- https://raw.githubusercontent.com/creationix/nvm/v0.39.7/install.sh | bash
  args:
    executable: /bin/bash
    chdir: "$HOME"
    creates: "$HOME/.nvm/nvm.sh"

- name: add lines to zsh
  blockinfile: 
    state: present
    insertbefore: "# Initialize modules."
    dest: "$HOME/.zshrc"
    marker: "# nvm ANSIBLE MANAGED BLOCK #"
    content: |
      export NVM_DIR=~/.nvm
      [ -s "$NVM_DIR/nvm.sh" ] && . "$NVM_DIR/nvm.sh"

- name: Install node
  ansible.builtin.shell: >
    . ./.nvm/nvm.sh && nvm install {{ item }}
  args:
    executable: /bin/bash
    chdir: "$HOME"
    creates: "$HOME/.nvm/versions/{{ item }}"
  loop:
    - 20.10.0
